### ISSUE TITLE
Can't load raw URLs unless there's a `/raw/` in the path

### ISSUE THREAD

**Issue by Likeyn** [wavepot/wavep0t#2]
Hey, first off I wanna say I've been a big fan of the concept when it first came out years ago, spent a lot of time on it and it was a lot of fun -- until it went down at some point. So I was very happy to randomly see it back online lately!

Anyway I noticed in your commits we're supposed to be able to get Wavepot to load code from a raw URL by passing it straight in the query string (which is a great idea that I want to use to rickroll friends), but it turns out it only works if the target path contains `/raw/` in it:
- doesn't load: https://wavepot.com/?raw.githubusercontent.com/Likeyn/wavepot-samples/master/NeverGonnaGiveYouUp.wavepot.js
- loads cuz' it's in a dir named `raw`: http://wavepot.com/?raw.githubusercontent.com/Likeyn/wavepot-samples/master/raw/NeverGonnaGiveYouUp.wavepot.js

I'm guessing it's due to these lines in the code:
- [sidebar.js#L181](https://github.com/wavepot/wavep0t/blob/12a35931ce78054a443bd952cc44508b2ea17ccd/sidebar.js#L181)
- [docs/build.js#L6165](https://github.com/wavepot/wavep0t/blob/12a35931ce78054a443bd952cc44508b2ea17ccd/docs/build.js#L6165)

Seemed to be an odd behavior tbf so I thought you'd want to know.
Cheers

**Comment by stagas** [comment]
Hey thanks for the issue! Happy to find people who used it :)

Should be working now: https://wavepot.com/?Likeyn/wavepot-samples/master/NeverGonnaGiveYouUp.wavepot.js
